# Generated by Django 3.1.7 on 2021-03-15 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_auto_20210315_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeeduser',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
