# Generated by Django 3.1.7 on 2021-03-18 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_rssfeeduser_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(max_length=2048)),
                ('published', models.DateTimeField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rss.rssfeeduser')),
            ],
        ),
    ]
