# Generated by Django 3.1.7 on 2021-03-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0004_feedentries'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedentries',
            name='external_id',
            field=models.CharField(default=1, max_length=2048, unique=True),
            preserve_default=False,
        ),
    ]
