# Generated by Django 3.1.7 on 2021-03-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0006_rssfeeduser_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeeduser',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
