# Generated by Django 3.1.7 on 2021-03-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0007_auto_20210319_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedentries',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
